### ISSUE TITLE
Make a tutorial how to run it?

### ISSUE THREAD

**Issue by Dajustin** [lucasmonstro/pytibia#19]
Can you make a vid how to run it or tell me how?

i installed the python version + all the requirements but still get core.py errors like:
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    main()
  File "test.py", line 26, in main
    hudImg = hud.core.getImgByCoordinate(screenshot, hudCoordinate)
  File "\pytibia-main\hud\core.py", line 34, in getImgByCoordinate
    return screenshot[coordinates[1]:coordinates[1] +
TypeError: 'NoneType' object is not subscriptable

would appriciate it.

**Comment by messias519** [comment]
> Can you make a vid how to run it or tell me how?
> 
> i installed the python version + all the requirements but still get core.py errors like: Traceback (most recent call last): File "test.py", line 41, in main() File "test.py", line 26, in main hudImg = hud.core.getImgByCoordinate(screenshot, hudCoordinate) File "\pytibia-main\hud\core.py", line 34, in getImgByCoordinate return screenshot[coordinates[1]:coordinates[1] + TypeError: 'NoneType' object is not subscriptable
> 
> would appriciate it.

The same here.

**Comment by Dajustin** [comment]
and when running test.py i get this:

`Traceback (most recent call last):
  File "test.py", line 41, in <module>
    main()
  File "test.py", line 25, in main
    hudCoordinate = hud.core.getCoordinate(screenshot)
  File "\pytibia-main\hud\core.py", line 18, in getCoordinate
    (rightSidebarArrows[0] - leftSidebarArrows[0]) // 2) + leftSidebarArrows[0]
TypeError: 'NoneType' object is not subscriptable`

tried to play with sizes and stuff but idk what im doing wrong here got hud same as in the battlelist picture

**Comment by lucasmonstro** [comment]
@Dajustin, @messias519  I'm working in optimization of some core functions like parsers and I forgot to add basic tutorials for PyTibia. Since I have 2 jobs, I dont have much time to work in PyTibia. I apologize for this.

To run pytibia You need to run in integral multiples using the mid size of hud. Im just detecting that size. 

Below, required settings to avoid colision in pixel detect and make the UI clean for PyTibia:

Interface > Show Cooldown Bar -> Enabled

Hud > Show HUD for Own Character > Disabled
Hud > Show HUD for Other Creatures > All Enabled
Hud > Show Customizable Status Bars > Disabled
Hud > Show Status Bar -> Enabled

Console > Show Status Messages of Others > Disabled
Console > Show Status Messages > Disabled
Console > Show Timestamps > Enabled

Game Window > Show Textual Effects > Disabled
Game Window > Show messages > Disabled
Game Window > Show combat frames > Enabled
Game Window > Scale Using Only Integral Multiples > Enabled

ActionBar > Show Action Bar 1 > Enabled
ActionBar > Show Action Bar 2 > Disabled
ActionBar > Show Assigned Hotkey for Action Button > Enabled
ActionBar > Show Amount of Assigned Objects > Enabled
ActionBar > Show Graphical Cooldown > Enabled
ActionBar > Show Action Button Tooltip > Disabled


Please use the current size of gameplay
![Sem Título](https://user-images.githubusercontent.com/1239463/184623654-40c04ee6-17c2-4150-9d21-7f02eca5b194.png)

Thats it!

**Comment by Dajustin** [comment]
Perfect will try it today. 
if you want i can make a Private youtube vid edited how to run with some basic features showing if i get the hang of it.

cheers

**Comment by Dajustin** [comment]
im getting this far with the settings i got from you.
`Traceback (most recent call last):
  File "test.py", line 41, in <module>
    main()
  File "test.py", line 25, in main
    hudCoordinate = hud.core.getCoordinate(screenshot)
  File "C:\Users\Björn\Desktop\pytibia-main\hud\core.py", line 18, in getCoordinate
    (rightSidebarArrows[0] - leftSidebarArrows[0]) // 2) + leftSidebarArrows[0]
TypeError: 'NoneType' object is not subscriptable`
![gefe](https://user-images.githubusercontent.com/98913651/185192401-3ee560fb-fd9a-4971-9562-908ab3bdee81.png)

thanks in advance

**Comment by Therealkorris** [comment]
> im getting this far with the settings i got from you. when running the test.py
> 
> `Traceback (most recent call last): File "test.py", line 41, in <module> main() File "test.py", line 25, in main hudCoordinate = hud.core.getCoordinate(screenshot) File "\pytibia-main\hud\core.py", line 18, in getCoordinate (rightSidebarArrows[0] - leftSidebarArrows[0]) // 2) + leftSidebarArrows[0] TypeError: 'NoneType' object is not subscriptable` ![gefe](https://user-images.githubusercontent.com/98913651/185192401-3ee560fb-fd9a-4971-9562-908ab3bdee81.png)
> 
> thanks in advance

I have the same issue, keep stopping at this message even when everything is set ut exactly as the guide, did you manage to find a solution?

**Comment by mariante** [comment]
```
PS C:\bb8t\pytibia> python main.py
Traceback (most recent call last):
  File "C:\bb8t\pytibia\main.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

![image](https://user-images.githubusercontent.com/9534835/193492909-34259618-2866-4347-80a2-e6f67873a766.png)

**Comment by Dajustin** [comment]
i will create a private youtube for you later
how i run it


Op za 10 sep. 2022 om 18:42 schreef Jonas Korani ***@***.***>:

**Comment by lucasmonstro** [comment]
Guys, this month I will release a v0 version to run in some OT servers. Soon I will make it runing in Global.

Be free to contact me on discord lucasmonstro#7433.
