### ISSUE TITLE
[BUG] - Is not possible to get the target on creature when it goes to the edges of the hud

### ISSUE THREAD

**Issue by mathiconical** [lucasmonstro/PyTibia#40]
**Describe the bug**
When the creature goes to out of bounds of HUD the bot cant keep find them.

**To Reproduce**
1. Go to some monster that have is ranged attack and which run with low life, like lizard in Chor.
2. Let some with low life.
3. Wait they goes through the HUD.
4. See the error.

**Screenshots**
![q2](https://user-images.githubusercontent.com/12927364/204063267-ff43b552-feed-4b2d-83ee-4822ed3ab89b.png)
![q1](https://user-images.githubusercontent.com/12927364/204063262-5a5bc27d-838e-474d-b734-2b5faf281294.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Tibia Version 12.64 [latest]

**Comment by lucasmonstro** [comment]
Looks like I need to calculate like I did to get the correctly monster bar. Going to fix it this weekend.

**Comment by lucasmonstro** [comment]
@mathiconical

[BOTTOM/RIGHT EDGES]

When trying to get target creature by right/bottom edge, looks like the creature do not appear in battle list and the creature bar isnt in hud anymore it means, there is no way to have this bug in right/bottom edge. So the final decision by PyTibia will be "you are not attacking monsters", you can see below:

![right_edge](https://user-images.githubusercontent.com/1239463/204082939-6ab9b0b7-5b8b-4362-892c-6ea38745e0aa.png)
![bottom_edge](https://user-images.githubusercontent.com/1239463/204083067-2cdade57-1233-48cf-a651-ea031a1e4e71.png)

[LEFT EDGE]

When creature is almost crossing limit, I think PyTibia can parse since the count of red border around monster should be 50+, so in below image example, everything will works fine:

![left_edge_almost_limit](https://user-images.githubusercontent.com/1239463/204083288-8429db2a-89dd-4996-9a22-d0a2d94a47e9.png)

![Sandcrawler](https://user-images.githubusercontent.com/1239463/204083524-a88be44a-fa6e-4544-b096-0b73b79c84f1.png)

When cross is more deep like image below, I think PyTibia can take target creature by horizontal borders since the sum of red horizontal borders could be (64(border size) * 4(gap)) * 2(lines) = 512pixels

![screenshot](https://user-images.githubusercontent.com/1239463/204083892-54f998bb-8e94-4427-952d-aec5e3923425.png)
![Sandcrawler](https://user-images.githubusercontent.com/1239463/204083895-16211461-2a11-4bec-9ed8-38ef20de4d8b.png)

A more deep cross. You can see images and response by PyTibia, still possible to take target creature:

![screenshot](https://user-images.githubusercontent.com/1239463/204084022-540ffabd-d743-4904-be1e-d720c67b8707.png)
![Sandcrawler](https://user-images.githubusercontent.com/1239463/204084060-85ce1fb5-c66c-4fbc-a05d-8c792c9e0d91.png)

```
[('Sandcrawler', 'monster',  True, [0, 2], [33269, 32291,     7], [248, 180])]
```

A 2x more deep cross. You can see images and response by PyTibia, still possible to take target creature:

![screenshot](https://user-images.githubusercontent.com/1239463/204084126-a2acf43c-3605-424b-b5a5-be868f09e4b0.png)
![Sandcrawler](https://user-images.githubusercontent.com/1239463/204084129-5b524561-1229-403c-b290-b32fda79853b.png)

```
[('Sandcrawler', 'monster',  True, [0, 2], [33269, 32291,     7], [248, 180])]
```

A 3x more deep cross. You can see images and response by PyTibia, still possible to take target creature:

![screenshot](https://user-images.githubusercontent.com/1239463/204084273-a6e7ac48-d5e4-4e83-9e15-424da021b6a9.png)
![Sandcrawler](https://user-images.githubusercontent.com/1239463/204084275-6d8d470e-4895-4a26-88e3-1f2cf8054235.png)


```
[('Sandcrawler', 'monster',  True, [0, 2], [33268, 32291,     7], [248, 180])]
```


[Conclusion]

Sometimes will fail because a tree or any object can hide the "red border around monster" and there is nothing to do, you can see examples below:

![monster_hidden_by_tree](https://user-images.githubusercontent.com/1239463/204084399-2bbb10cd-bf62-4804-be23-c43d465b7392.png)

[Solution]

We can add a timer to switch when the target creature is lost!

**Comment by mathiconical** [comment]
@lucasmonstro Very useful solutions, working perfectly now.

**Comment by lucasmonstro** [comment]
@mathiconical I'm going to:
-- calculate with fewer pixels for 720p resolutions
-- since creature is in the edge, I need to check all monsters to reduce pixels count

**Comment by lucasmonstro** [comment]
Done!
