### ISSUE TITLE
[BUG] - Creature has wrong sqm alignment on the HUD

### ISSUE THREAD

**Issue by mathiconical** [lucasmonstro/PyTibia#41]
**Describe the bug**
Some creatures like Minotaurs, Amazons and much more have wrong alignment on the HUD, the bot can't find the exaclty position of the corpse to loot it.

**To Reproduce**
1. Go to kill some dragons and loot it.
2. Go to amazon's or minotaur's and loot it.
3. See error

**Expected behavior**
Loot the corpses correctly.

**Screenshots**
![q1](https://user-images.githubusercontent.com/12927364/204063575-45d7398d-b887-4de1-ae8c-f58b45510a56.png)
![q2](https://user-images.githubusercontent.com/12927364/204063579-25f8cf4a-ae1e-42d0-adba-b9c3c7010a1d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Tibia Version 12.64 [latest]

**Comment by lucasmonstro** [comment]
I summoned several creatures to know which ones had this misalignment and there are several.
Next step I will print each creature to get the alignment distance because they have different distances.

You can see below the creatures that have misalignment made by @GuizinhoYT:

[A]
Achad
Acolyte Of Darkness
Acolyte Of The Cult
Adept Of The Cult
Adventurer
Agrestic Chicken
Amazon
Ancient Lion Archer
Angry Adventurer
Animated Mummy
Apprentice Sheng
Armenius
Ascending Ferumbras
Assassin
Axeitus Headbanger
[B]
Bandit
Bane Of Light
Banshee
Barbaria
Barbarian Bloodwalker
Barbarian Brutetamer
Barbarian Headsplitter
Barbarian Skullhunter
Baron Brute
Battlemaster Zunzu
Berserker Chicken
Bibby Bloodbath
Biting Cold
Black Knight
Black Sheep
Blazing Fire Elemental
Bovinus
Brittle Skeleton
Brutus Bloodbeard
Burning Gladiator
[C]
Captain Jones
Cave Parrot
Centipede
Chicken
Colerian The Barbarian
Crazed Beggar
Crazed Dwarf
Crypt Defiler
Crypt Shambler
Crypt Warrior
Cult Believer
Cult Enforcer
Cult Scholar
Cursed Gladiator
[D]
Darakan The Executioner
Dark Apprentice
Dark Druid
Dark Magician
Dark Monk
Dark Paladin
Dark Sorcerer
Dawnfire Asura
Deadeye Devious
Death Priest Shargon
Deathslicer
Deer
Defiler
Demon Parrot
Demon Skeleton
Depowered Minotaur
Destabilized Ferumbras
Dharalion
Dirtbeard
Doctor Perhaps
Doom Deer
Druid Familiar
Druid's Apparition
Dryad
Dwarf
Dwarf Geomancer
Dwarf Guard
Dwarf Miner
Dwarf Soldier
Dworc Fleshhunter
Dworc Venomsniper
Dworc Voodoomaster
[E]
Ekatrix
Elder Mummy
Elf
Elf Arcanist
Enlightened Of The Cult
Enraged Soul
Evil Sheep
Evil Sheep Lord
[F]
Falcon Knight
Falcon Paladin
Fallen Mooh'tah Master Ghar
Fernfang
Feroxa
Ferumbras
Ferumbras Mortal Shell
Ferumbras Soul Splinter
Fiery Blood
Fire Devil
Fire Elemental
Firestarter
Flame Of Omrafir
Flamingo
Foreman Kneebiter
Frost Flower Asura
Frost Troll
Frostfur
Frozen Minion
Furious Troll
Fury
Furyosa
[G]
Gang Member
Gargoyle
Ghost
Ghost Wolf
Ghoul
Gladiator
Glooth Bandit
Glooth Brigand
Gnorre Chyllson
Goblin
Goblin Assassin
Goblin Leader
Goblin Scavenger
Goldhanded Cultist
Grand Canon Dominus
Grand Chaplain Gaunder
Grand Commander Soeren
Grandfather Tridian
Grave Robber
Greater Death Minion
Grimgor Guteater
Grynch Clan Goblin
[H]
Hero
Honour Guard
Hunter
[I]
Ice Witch
Incredibly Old Witch
Infernalist
[J]
Jailer
Jesse The Wicked
[K]
Knight Familiar
Knight's Apparition
Kraknaknork
[L]
Lady Tenebris
Lesser Death Minion
Lesser Fire Devil
Lethal Lissy
Lion Archer
Lizard Noble
[M]
Mad Scientist
Mad Technomancer
Malicious Minion
Mammoth
Man In The Cave
Mechanical Fighter
Mezlon The Defiler
Midnight Asura
Minotaur
Minotaur Archer
Minotaur Bruiser
Minotaur Cult Follower
Minotaur Cult Prophet
Minotaur Cult Zealot
Minotaur Guard
Minotaur Invader
Minotaur Mage
Minotaur Occultist
Minotaur Poacher
Mirror Image
Misguided Bully
Misguided Thief
Monk
Monk Of The Order
Morik The Gladiator
Mountain Troll
Muglex Clan Assassin
Muglex Clan Footman
Muglex Clan Scavenger
Mummy
Mushroom Sniffer
Mutated Human
[N]
Necromancer
Necromancer Servant
Necropharus
Nightfiend
Nightmarish Dream
Nomad
Novice Of The Cult
[O]
Ogre Ruffian
Orc
Orc Berserker
Orc Cult Fanatic
Orc Cult Inquisitor
Orc Cult Minion
Orc Cult Priest
Orc Cultist
Orc Leader
Orc Shaman
Orc Spearman
Orc Warlord
Orc Warrior
Orcus The Cruel
Overcharged Disruption
[P]
Paladin Familiar
Paladin's Apparition
Parrot
Party Skeleton
Percht
Percht Minion
Pig
Pirate Buccaneer
Pirate Corsair
Pirate Cutthroat
Pirate Ghost
Pirate Marauder
Pirate Skeleton
Plagirath
Poacher
Priestess
[R]
Renegade Knight
Renegade Orc
Retainer Of Baeloc
Rift Phantom
Robby The Reckless
Rukor Zad
[S]
Salamander Trainer
Sandcrawler
Scar Tribe Shaman
Scar Tribe Warrior
Schiach
Sheep
Skeleton
Skeleton Elite Warrior
Skeleton Warrior
Smuggler
Smuggler Baron Silvertoe
Sorcerer Familiar
Sorcerer's Apparition
Soulless Minion
Spawn Of Havoc
Spectral Scum
Stalker
Starving Wolf
Svoren The Mad
Swamp Troll
Swan Maiden
[T]
Teleskor
The Axeorcist
The Cold Of Winter
The Dark Dancer
The Enraged Thorn Knight
The Hag
The Heat Of Summer
The Horned Fox
The Shielded Thorn Knight
The Sinister Hermit
The Weakened Count
Tomb Servant
Tormented Ghost
Troll
Troll Legionnaire
[U]
Undead Mine Worker
Undead Prospector
Usurper Archer
[V]
Valkyrie
Vampire
Vampire Pig
Vicious Squire
Vile Grandmaster
[W]
Warlock
Warlord Ruzad
Warm Fire
Waspoid
Weakened Frazzlemaw
Weeping Soul
Whirling Blades
Wild Fire Magic
Wild Fury Magic
Wild Horse
Wild Nature Magic
Wild Warrior
Wild Water Magic
Willi Wasp
Winter Wolf
Witch
Wolf
Woodling
[X]
Xenia
[Y]
Yaga The Crone
Yakchal
Young Troll
[Z]
Zarabustor
Zushuka

**Comment by lucasmonstro** [comment]
I did from A to R and Im going to finish the calcs today and I will open a PR. When a finish the calcs, I will update the comment. Watch out @mathiconical!

The numbers after the monster name means the x, y of misalignment from the perfect SQM!

[A]
Achad 16,16
Acolyte Of Darkness 16,16
Acolyte Of The Cult 16,16
Adept Of The Cult 16,16
Adventurer 16,16
Agrestic Chicken 16,16
Amazon 16,16
Ancient Lion Archer 4,12
Angry Adventurer 16,16
Animated Mummy 16,16
Apprentice Sheng 22,22
Armenius 16,16
Ascending Ferumbras 16,16
Assassin 16,16
Axeitus Headbanger 16,16

[B]
Bandit 16,16
Bane Of Light 16,16
Banshee 16,16
Barbaria 16,16
Barbarian Bloodwalker 16,16
Barbarian Brutetamer 16,16
Barbarian Headsplitter 16,16
Barbarian Skullhunter 20,20
Baron Brute 16,16
Berserker Chicken 16,16
Bibby Bloodbath 16,16
Biting Cold 16,16
Black Knight 16,16
Black Sheep 8,0
Blazing Fire Elemental 16,16
Bovinus 16,16
Brittle Skeleton 16,16
Brutus Bloodbeard 16,16
Burning Gladiator 16,16

[C]
Captain Jones 0,16
Cave Parrot 4,0
Centipede 8,0
Chicken 16,16
Colerian The Barbarian 16,16
Crazed Beggar 16,16
Crazed Dwarf 16,16
Crypt Defiler 16,16
Crypt Shambler 16,16
Crypt Warrior 16,16
Cult Believer 16,16
Cult Enforcer 16,16
Cult Scholar 16,16
Cursed Gladiator 16,16

[D]
Darakan The Executioner 16,16
Dark Apprentice 16,16
Dark Druid 16,16
Dark Magician 16,16
Dark Monk 16,16
Dark Paladin 16,16
Dark Sorcerer 16,16
Dawnfire Asura 16,16
Deadeye Devious 16,16
Death Priest Shargon 16,16
Deathslicer 16,16
Deer 16,16
Demon Parrot 4,0
Demon Skeleton 16,16
Depowered Minotaur 16,16
Destabilized Ferumbras 16,16
Dharalion 16,16
Dirtbeard 16,16
Doctor Perhaps 16,16
Doom Deer 16,16
Druid Familiar 16,16
Druid's Apparition 16,16
Dryad 16,16
Dwarf 16,16
Dwarf Geomancer 16,16
Dwarf Guard 16,16
Dwarf Miner 16,16
Dwarf Soldier 16,16
Dworc Fleshhunter 16,16
Dworc Venomsniper 16,16
Dworc Voodoomaster 16,16

[E]
Ekatrix 16,16
Elder Mummy 16,16
Elf 16,16
Elf Arcanist 16,16
Enlightened Of The Cult 16,16
Enraged Soul 16,16
Evil Sheep 8,0
Evil Sheep Lord 8,0

[F]
Falcon Knight 4,12
Falcon Paladin 4,12
Fallen Mooh'tah Master Ghar 16,16
Fernfang 16,16
Feroxa 16,16
Ferumbras 16,16
Ferumbras Mortal Shell 16,16
Ferumbras Soul Splinter 16,16
Fiery Blood 16,16
Fire Devil 16,16
Fire Elemental 16,16
Firestarter 16,16
Flame Of Omrafir 16,16
Flamingo 16,16
Foreman Kneebiter 16,16
Frost Flower Asura 16,16
Frost Troll 16,16
Frostfur 16,4
Frozen Minion 16,16
Furious Troll 16,16
Fury 16,16
Furyosa 16,16

[G]
Gang Member 16,16
Ghost 16,16
Ghost Wolf 16,4
Ghoul 16,16
Gladiator 16,16
Glooth Bandit 16,16
Glooth Brigand 16,16
Gnorre Chyllson 16,16
Goblin 16,16
Goblin Assassin 16,16
Goblin Leader 16,16
Goblin Scavenger 16,16
Goldhanded Cultist 16,16
Grand Canon Dominus 4,12
Grand Chaplain Gaunder 4,12
Grand Commander Soeren 4,12
Grandfather Tridian 16,16
Grave Robber 16,16
Greater Death Minion 16,16
Grimgor Guteater 16,16
Grynch Clan Goblin 16,16

[H]
Hero 16,16
Honour Guard 16,16
Hunter 16,16

[I]
Ice Witch 16,16
Incredibly Old Witch 16,16
Infernalist 16,16

[J]
Jailer 16,16
Jesse The Wicked 16,16

[K]
Knight Familiar 16,16
Knight's Apparition 16,16
Kraknaknork 16,16

[L]
Lady Tenebris 16,16
Lesser Death Minion 16,16
Lesser Fire Devil 16,16
Lethal Lissy 16,16
Lion Archer 4,12

[M]
Mad Scientist 16,16
Mad Technomancer 16,16
Malicious Minion 16,16
Man In The Cave 16,16
Mechanical Fighter 16,16
Mezlon The Defiler 16,16
Midnight Asura 16,16
Minotaur 16,16
Minotaur Archer 16,16
Minotaur Bruiser 16,16
Minotaur Cult Follower 16,16
Minotaur Cult Prophet 16,16
Minotaur Cult Zealot 16,16
Minotaur Guard 16,16
Minotaur Invader 16,16
Minotaur Mage 16,16
Minotaur Occultist 16,16
Minotaur Poacher 16,16
Mirror Image 16,16
Misguided Bully 16,16
Misguided Thief 16,16
Monk 16,16
Monk Of The Order 16,16
Morik The Gladiator 16,16
Mountain Troll 16,16
Muglex Clan Assassin 16,16
Muglex Clan Footman 16,16
Muglex Clan Scavenger 16,16
Mummy 16,16
Mushroom Sniffer 16,0
Mutated Human 16,16

[N]
Necromancer 16,16
Necromancer Servant 16,16
Necropharus 16,16
Nightfiend 16,16
Nightmarish Dream 16,16
Nomad 16,16
Novice Of The Cult 16,16

[O]
Orc 16,16
Orc Berserker 16,16
Orc Cult Fanatic 16,16
Orc Cult Inquisitor 16,16
Orc Cult Minion 16,16
Orc Cult Priest 16,16
Orc Cultist 16,16
Orc Leader 16,16
Orc Shaman 16,16
Orc Spearman 16,16
Orc Warlord 16,16
Orc Warrior 16,16
Orcus The Cruel 16,16
Overcharged Disruption 16,16

[P]
Paladin Familiar 16,16
Paladin's Apparition 16,16
Parrot 4,0
Party Skeleton 16,16
Percht 8,8
Percht Minion 16,16
Pig 16,0
Pirate Buccaneer 16,16
Pirate Corsair 16,16
Pirate Cutthroat 16,16
Pirate Ghost 0,16
Pirate Marauder 16,16
Pirate Skeleton 16,16
Poacher 16,16
Priestess 16,16

[R]
Renegade Knight 16,16
Renegade Orc 16,16
Retainer Of Baeloc 16,16
Rift Phantom 16,16
Robby The Reckless 16,16
Rukor Zad 16,16

**Comment by lucasmonstro** [comment]
@mathiconical all calcs of misalignment are ready, going to open pull request today!

**Comment by lucasmonstro** [comment]
@mathiconical look this commit 60a2a7fd295524545f098a5e44def0a6f00ff39f

Already finished into the config, going to implement in cavebot and make some tests.

**Comment by lucasmonstro** [comment]
@mathiconical 

Did some improvements here 3fcedad3e96ac8430eec103f041283b57a38a2dc. Still needing improves when creature is on the edges because windowCoordinate of the creature still in the wrong place. Going to fix it ASAP.

**Comment by mathiconical** [comment]
@lucasmonstro Working correctly now.

**Comment by lucasmonstro** [comment]
@mathiconical everything working like a charm! Thanks for your report.
